# make a mutation dictionary

mut_dict={

  "A": {
    "T","G","C"
    },
  "T": {
    "A","G","C"
    },
  "G": {
    "A","C","T"
    },
  "C": {
    "A","G","T"
    }
}

import sys
outFile=open(sys.argv[1],'wt')

# Define the blocks
# use the reverse complement sequences
# The following sequences are the RC of (5'25nt + block + 3'19 nt)
# use capitalized letters

block1=list("CTGCCTGCGGAGGGCGCGGTTCTCCTCCTCCACCTCGCGCATGCGCACCTCCAGGCTCTCGCGCTCCCGCTGGCTGGAGGCCGTGTACCTGGGGCTGTGTGCCTGGGACTCCAGCGGTGACAGAGACACGGGCTTTCCATCTTCGAAGCTCCCAGAAAACAGGTAAATCCAGGTGATGGCTGGGATGCAGAGAAGACTCAACGAGGCAGCCAAGAATTTCCGTCTCCCCCTGCAGATTCCCAGCATTCTAGAACCGGTACCAAGTGACGAT")
block2=list("TTGACCAGGGTGACGACATCCCGGCTGGCATTGTATCCGGCGCAGACAATAGCAACGTGGATTGTCTCGCATTTCTCCACGACCGGCTGCTGCCCACACTCGGAGCTGTTGCCTGCCACGATGCCAGCCCGAAGGTTCTCGCTGTCTCCAGTGCCCTCCTCCATGGAGTAGGTCTTGGAGTGGTTGCCTCGGCGATGGGATGGGGCTCGGCCCTGGGCCAGGCTGAGCTGCCTGCGGAGGGCGCGGTTCTCCTCCTCCACCTCGCGCATGC")
block3=list("TGGCAGGAAGAGTCTTGGTCAGGACAAGCTTCATCAGACCATAAATCCCAGAGTAATGTTTATTGGGGATCCAGGAAACTTCAGACTTGAGCTCGTCTGCATTGTAGAAGTCCACACGCACAGCGGGCACCATCCAGGTCTGGAAGAGCGTGGCCAGGATCTGCTCCGCAATGGAGTCAGCAATAAGGTGGAAGTGCAGAGGGTTCCGTCTATGGAACAGGACGGATTTGACCAGGGTGACGACATCCCGGCTGGCATTGTATCCGGCGCA")
block4=list("CTTCCGCAGCTTATCCAGAAGTAACAGGATCACCCCTGTGTTGTAGCCTCTTCCAAGGGCTGGCCATGGGCGGTGATTTTTCCACAGGTTTCCAAGGTACCAGTCACTCTGGTTCTCCACCAAGCCCAGGACTTGCTGACCTTTGAACTTGTGGAACACAGCCCACAGCTCTGCAATGTCAGTGGCAAAGGTGATATCCGTGTCAAGGACGATGACTCTCTCCAGGTTGGCAGGAAGAGTCTTGGTCAGGACAAGCTTCATCAGACCATAA")
block5=list("TTGGGGGAGTTCCAGTGAATGACCTTTAGATCAGACACGTCTCTGTAGCACTGCTCGGAGCGGGTGTGGTCTGACAGCTGCACATTCCAGAAGCAGGGGAGCTGGTACACAAGGAAGGGGTTTTGTTTGATGACGGCATTGAAAATATCCTGGTCAGCTAAGGATGTAGAGAGCATGCCCATGAGCTCCCTCTCTGCGGTCAGCCTCCACATCTGCTCCCATTTCATCTTCCGCAGCTTATCCAGAAGTAACAGGATCACCCCTGTGTTGT")
block6=list("GGAAGTACAGGTGGGTGCGGTGGACAGTGAAGCGCTCTCGCCGGAACTCATAGCACAGGTCGTCCTCGTCCAGCTCAGACAGCTGCTTCTGGAGGTTTTCACTGTTGACATCAGCCTCACTGGGGCAGCCAAACAGTTCCCGCCTCAGAAGATTGCCGTCATACTCCAGGAAGGTCAGGTAGAGGTTGCGAAAAAACTCCACATGCTTGTTCTTCACCCGGAGCTTCTTGGGGGAGTTCCAGTGAATGACCTTTAGATCAGACACGTCTCT")
block7=list("CTTGTACACGATGTGGTAGCCCACGTTGTGGCGGCTCATAAGCACCTCAGAGCCCTGTGCGTAGCGGAGGAACTGCTGGGCCTCGGCGTCTGACAGGTAGAGGGCCAGGCTGATGGGCCCCTCCCAGTGCTTGCAGATGGCCTCCAGCATCTGGAGCCTGTCCATGGACAGCTGAGCGACCAGGGTGACGTCCGTGCTGTCTGCTGCAGGCTCATACTCGTAGTGCAGGAAGTACAGGTGGGTGCGGTGGACAGTGAAGCGCTCTCGCCGG")
block8=list("TCCGCTTTTGACTTGGGGAAGGACAGCCGGTAGCGCAGTGTCTCGAACGCGGGGACAATCATTGCTTTCTTGGTGTTGGCAAGATCGAGCTGGATGACAGACTTCCTGAGGTACTCATAGAGCCCATACATGGGCAGGAAGTCAATGTCAGACAGGAACATGTAGGGAGTGCTGATGTGCTTCATGGCCACGTTGCGCAGCAGGTTCACGGGGTAGAACTGGCCCTCCTTGTACACGATGTGGTAGCCCACGTTGTGGCGGCTCATAAGCA")
block9=list("GCTCCATGATATGAGCCACTTTGTTCCAGCCAAAGCCTACAAACCTCCGGTCGTACTCCGGGCAGTCACGTCTCACAACAACATACGGCTCAAAATCGGCCTCCCACTCAACCCGGTAAGGCGTGGTGGCGGTCCGCCACTTGGCGAAGTTTGTGGGTGCGTGGCCTTTCGTCCAGACGTGGTACCTGAATGTGAAGAGGGTCCCCATGTCCAGCATTGACAGCAACTCCGCTTTTGACTTGGGGAAGGACAGCCGGTAGCGCAGTGTCTC")
block10=list("ACTTTTCGGGGGATCCCTAGCTGTTGTTCTCGGCTGTGAGATATTTCAGGGCAGCAAAGCCGTAGCGGCGGGACATGTCCTGCTGAAACTCTTCCTTGAGGGTTTTGAGACAGATGCGGTATTGCTTGTTGGAACGGAACTTGGTAATGTCGAAGCTGGGGGCATGAGGCATGTGGATCATGTAGGCGTTGGGCAGCACAATGAACTCATACTCCTGCACATCCAGCTCCATGATATGAGCCACTTTGTTCCAGCCAAAGCCTACAAAC")

block=[block1,block2,block3,block4,block5,block6,block7,block8,block9,block10]

# Define the overhangs
# block_specific_8_nt + GGTCTC + random_5_nt
# last 4 nt cannot be in the block
overhang1="AGACCCTAGGTCTCATATC"
overhang2="TTGCGCTGGGTCTCCCTAG"
overhang3="GCCGGGATGGTCTCAATTC"
overhang4="AAGCTAATGGTCTCAGCGC"
overhang5="AACAGTAAGGTCTCGCGCC"
overhang6="AAGTTGTCGGTCTCAATAA"
overhang7="CGACCACCGGTCTCAAATC"
overhang8="GAGATGTCGGTCTCGGTTT"
overhang9="GGAGCAGCGGTCTCGGATC"
overhang10="ATAAGATGGGTCTCCCTTA"
overhang=[overhang1,overhang2,overhang3,overhang4,overhang5,overhang6,overhang7,overhang8,overhang9,overhang10]

# Generate mutations

flag=0

for i in range(0,10):
    for j in range(19,len(block[i])-25):

        for x in mut_dict:
            for y in mut_dict[x]:
                if block[i][j]==x:
                    mutseq=overhang[i]+"".join(block[i][j-19:j])+y+"".join(block[i][j+1:j+26])
                    flag+=1
                    outFile.write(">"+str(flag)+'\n'+mutseq+'\n')

outFile.close()
