# make a mutation dictionary

mut_dict={

  "A": {
    "T","G","C"
    },
  "T": {
    "A","G","C"
    },
  "G": {
    "A","C","T"
    },
  "C": {
    "A","G","T"
    }
}

import sys
outFile=open(sys.argv[1],'wt')

# Define the blocks
# use the RC sequence

block1=list("GGCGGGTAGGGGAGCGTGTCGGCTGCCACCACCACGGGCTGGGCTGGGTCTTGCTGCAGGAAGGAGTCTACCAGCTCGGGCACCGCGTTGTCAAATGCCTCGAACTCCCGCACCAGGACGGTGACACGGGGGCCGGCAGCAGAGGCACGACGGGGCCCCCGGGCCCGGGAATTCCTAGGCTGGTGCTGCAGCCACGAGACATAGAAGAGGACCAGAAGGTTGAGGGTGATGGCGGCCGCCAGGGCAGCCTGGCAGCGGGTGAGCCGCATTCTAGAACCGGTACCAAGTGACGAT")
block2=list("GACGTTCAGGGCCAGGCACCTGGCAGGGTTGGCCGTGGCAACCGGGGCGGCCACCAGACGTGCGCTTCCTGCGCGGAGCGCCTCCACCATGCGCTCCAGCAGGCCAGGTGCCTCAGCCCGCGCCCCATCAGGTACTAGGGCCACAAACTCGGTGGCCACGTAGGTCTCCGGGCGCGAGGCTGCGGCTGGCCGGTCCAGGGCGGGCTGGAGCAGCGCCAGACGCACGTTGGGGATGCGGGGCAGGGCCAGGGGCGGGTAGGGGAGCGTGTCGGCTGCCACCACCACGGGCTGGGC")
block3=list("CCTTCCAGCGCGCGTGGGCCGTGGCCAGCGGGGGCTGGCGCGCCGCGGCGAAGGTCAAGTCCAGCAGCTGCACCGCCCAGCCGCGAAGGGCGGTCTGCAGAAAGAGGCTGGTGCCCACCGGCCGGGCCAGGGGCGCCGAGAGGTTGAAGAGGTCGCGGGCGCGCAGGAGCACCACAGCATCTCCGTCCAGGGCGTCGCAGCGGGGCGCGGCGGGGGCTGCGCCATAGCGGGCGGTCCACTCTCGCAGGCTGACGTTCAGGGCCAGGCACCTGGCAGGGTTGGCCGTGGCAACCG")
block4=list("TAGCGCACGCCCGCAGCCTCCAGCACGCCCACCACATAGCGGGCGGTCTCGCGCAGCGCGCGCAGGCAGCAGGGGGGCGTCCAGCGCTCCTCGTAGAGGTAGGCGGGCGTGTCGCCCACCACGGTTCCGAAGCAGCGCGTGGTCTCCTTGTTGCAGCCGAACCACTCCAGCCGCCCGCCTTCCCAGCTCACTAGGCGGATGCCCAGCGCGCGGAGCAGCGCCGCCCGCCGAGCGCGTCCCTCGCGCTCAGCCTTCCAGCGCGCGTGGGCCGTGGCCAGCGGGGGCTGGCGCGCC")
block5=list("GCGGGGGTAGAAGGGCCACAGGTCCACGTGCAAGTGGTTGCTTTCGCTGTACTGCACGCGGAAAAAGTCGCCCTCGACCGCCTTCTCCCATACGAAGCCGCGCTCATCCACCACCGAGCCGGCCTCTGCCCCCCGCAGCTGCTCGCAGTTGCCCACGTCCTCCAAGTAGATGCCCAGGTCCACGTCGTAGTCCCATGGGATGATGTCCCCGTGGCGGGCGGCCCCCAGCAGTGAGCCGCCCTCGAGCCAGTAGCGCACGCCCGCAGCCTCCAGCACGCCCACCACATAGCGGGC")
block6=list("ACTTTTCGGGGGATCCTCAGCCGCTTCCCGTCAGACTCAGCAGTGCCGGGTTGGGGTACTGGGGGTTCTCGATGACCCCGGGCCCGAACTTGAGCTCCAGGAAGCGGCGGTAGTTGTTAGGCGCCTGCGCCACGAAGCCGGCAAAGGGCAGGGGCACCAGCGGCTGCAGGAAGTGCTCGGGAAACTCCACATCCTGCCGGTGGTCCAGCCACGTGTCCTTGGTCATGACGCCATTGCGGGGGTAGAAGGGCCACAGGTCCACGTGCAAGTGGTTGCTTT")
block=[block1,block2,block3,block4,block5,block6]

# Define the overhangs
overhang1="CTGTAGTTCGTCTCCGTAC"
overhang2="CCACATCGCGTCTCCTGAC"
overhang3="CTCTTCTGCGTCTCTTACG"
overhang4="GGATGACTCGTCTCCACGT"
overhang5="AACACGCTCGTCTCTCTGA"
overhang6="AGGGAGGTCGTCTCGGATC"
overhang=[overhang1,overhang2,overhang3,overhang4,overhang5,overhang6]

# Generate mutations

flag=0

for i in range(0,6):
    for j in range(19,len(block[i])-25):

        for x in mut_dict:
            for y in mut_dict[x]:
                if block[i][j]==x:
                    mutseq=overhang[i]+"".join(block[i][j-19:j])+y+"".join(block[i][j+1:j+26])
                    flag+=1
                    outFile.write(">"+str(flag)+'\n'+mutseq+'\n')

outFile.close()
